In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("movie_metadata.csv")

df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [2]:
df.info()
df.shape
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5029 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4993.000000,5028.000000,4939.000000,5020.000000,5036.000000,4.159000e+03,5.043000e+03,5043.000000,5030.000000,5022.000000,4.551000e+03,4935.000000,5030.000000,5043.000000,4714.000000,5043.000000
mean,140.194272,107.201074,686.509212,645.009761,6560.047061,4.846841e+07,8.366816e+04,9699.063851,1.371173,272.770808,3.975262e+07,2002.470517,1651.754473,6.442138,2.220403,7525.964505
std,121.601675,25.197441,2813.328607,1665.041728,15020.759120,6.845299e+07,1.384853e+05,18163.799124,2.013576,377.982886,2.061149e+08,12.474599,4042.438863,1.125116,1.385113,19320.445110
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,50.000000,93.000000,7.000000,133.000000,614.000000,5.340988e+06,8.593500e+03,1411.000000,0.000000,65.000000,6.000000e+06,1999.000000,281.000000,5.800000,1.850000,0.000000
50%,110.000000,103.000000,49.000000,371.500000,988.000000,2.551750e+07,3.435900e+04,3090.000000,1.000000,156.000000,2.000000e+07,2005.000000,595.000000,6.600000,2.350000,166.000000
75%,195.000000,118.000000,194.500000,636.000000,11000.000000,6.230944e+07,9.630900e+04,13756.500000,2.000000,326.000000,4.500000e+07,2011.000000,918.000000,7.200000,2.350000,3000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,1.221550e+10,2016.000000,137000.000000,9.500000,16.000000,349000.000000

In [3]:
df.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      14
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [8]:
df.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [9]:
df['gross'] = pd.to_numeric(df['gross'], errors='coerce')
df['budget'] = pd.to_numeric(df['budget'], errors='coerce')

In [10]:
df['profit'] = df['gross'] - df['budget']

In [11]:
df[['movie_title','gross','budget','profit']].head()

,movie_title,gross,budget,profit
0,Avatar,760505847.0,237000000.0,523505847.0
1,Pirates of the Caribbean: At World's End,309404152.0,300000000.0,9404152.0
2,Spectre,200074175.0,245000000.0,-44925825.0
3,The Dark Knight Rises,448130642.0,250000000.0,198130642.0
4,Star Wars: Episode VII - The Force Awakens,NaN,NaN,NaN

In [12]:
df[['movie_title','profit']]

                                     movie_title       profit
0                                         Avatar  523505847.0
1       Pirates of the Caribbean: At World's End    9404152.0
2                                        Spectre  -44925825.0
3                          The Dark Knight Rises  198130642.0
4     Star Wars: Episode VII - The Force Awakens          NaN
...                                          ...          ...
5038                     Signed Sealed Delivered          NaN
5039                               The Following          NaN
5040                        A Plague So Pleasant          NaN
5041                            Shanghai Calling          NaN
5042                           My Date with Drew      84122.0

[4998 rows x 2 columns]

In [13]:
df.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes', 'profit'],
      dtype='object')

In [14]:
df[['movie_title','profit']].sort_values(by='profit', ascending=False).head(10)

                                    movie_title       profit
0                                        Avatar  523505847.0
29                               Jurassic World  502177271.0
26                                      Titanic  458672302.0
3024         Star Wars: Episode IV - A New Hope  449935665.0
3080                 E.T. the Extra-Terrestrial  424449459.0
17                                 The Avengers  403279547.0
509                               The Lion King  377783777.0
240   Star Wars: Episode I - The Phantom Menace  359544677.0
66                              The Dark Knight  348316061.0
439                            The Hunger Games  329999255.0

In [16]:
df.groupby('director_name')['imdb_score'].mean().sort_values(ascending=False).head(10)

director_name
John Blanchard      9.5
Mitchell Altieri    8.7
Sadyk Sher-Niyaz    8.7
Cary Bell           8.7
Mike Mayhall        8.6
Charles Chaplin     8.6
Ron Fricke          8.5
Damien Chazelle     8.5
Raja Menon          8.5
Majid Majidi        8.5
Name: imdb_score, dtype: float64

In [17]:
df['genres'].str.split('|').explode().value_counts().head(10)

genres
Drama        2571
Comedy       1862
Thriller     1396
Action       1143
Romance      1098
Adventure     914
Crime         883
Sci-Fi        611
Fantasy       604
Horror        556
Name: count, dtype: int64

In [18]:
df.groupby('actor_1_name')['num_critic_for_reviews'].mean().sort_values(ascending=False).head(10)

actor_1_name
Phaldut Sharma      738.0
Peter Capaldi       654.0
Craig Stark         596.0
Bérénice Bejo       576.0
Suraj Sharma        552.0
Ellar Coltrane      548.0
Mike Howard         546.0
Lou Taylor Pucci    543.0
Maika Monroe        533.0
Tim Holmes          525.0
Name: num_critic_for_reviews, dtype: float64

In [20]:
df.groupby('actor_1_name')['num_voted_users'].mean().sort_values(ascending=False).head(10)

actor_1_name
Mhairi Calvey        736638.000000
Scatman Crothers     645187.000000
Anil Kapoor          641997.000000
Wayne Knight         613473.000000
Phaldut Sharma       582917.000000
John Ratzenberger    549421.666667
Mathieu Kassovitz    534262.000000
Sharlto Copley       531737.000000
Emilia Fox           497946.000000
Ivana Baquero        467234.000000
Name: num_voted_users, dtype: float64